name: Build site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build the site
        run: |
          deno task build --location=https://wotringer.github.io/test
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.0.1
        with:
          build_dir: site/_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
